module Slh
  class Cli < Thor
    include Thor::Actions
    def self.source_root
      File.dirname(__FILE__)
    end

    desc 'generate_shims', 'Generates shim files in target language to use within your shibbified app'
    method_option :target_language,
      type: :string,
      default: 'php', # THIS WILL BE DYNAMIC BASED ON config DSL later.
      desc: 'Sets what language the shib controller and model shim code should be in',
      aliases: '-t',
      banner: 'TARGET_LANGUAGE'
    def generate_shims
      template("templates/model_shim.#{options[:target_language]}.erb", "slh_model_shim.#{options[:target_language]}")
      template("templates/controller_shim.#{options[:target_language]}.erb", "slh_controller_shim.#{options[:target_language]}")
    end

    protected
    def generate_shims_header_text
      ERB.new(<<-EOS
This code was programatically generated by Shibboleth's Lil Helper
via the generate_shims command, it'd be wise not to edit this.
Version <%= ShibbolethsLilHelper::VERSION %>
At <%= Time.now.to_s(:db) %>
      EOS
      ).result(binding)
    end
  end
end
